### ISSUE TITLE
Several DOI URL variants possible

### ISSUE THREAD

**Issue by katrinleinweber** [fiduswriter/fiduswriter-citation-api-import#4]
Because of https://www.doi.org/doi_handbook/3_Resolution.html#3.8 there are most likely DOU URL variants floating around that have `https` or `http`, with or without `dx.`.

1. Might this code section need a reg-ex to catch them all? Maybe `https://(dx\.)?doi\.org`?

https://github.com/fiduswriter/fiduswriter-citation-api-import/blob/8b8803c140b563eff0d4083bb5973f03a7a5b775/citation-api-import/static/js/es6_modules/citation-api-import/templates.js#L120

2. Also, [some statics links (in tests, I presume)](https://github.com/search?q=org%3Afiduswriter+dx.doi&type=Code) could be updated. Shall I?

**Comment by johanneswilm** [comment]
@katrinleinweber Thanks! I had no idea about this.

In the case 1 you mention, we are replacing a value that comes from crossref. If I recall correctly we do that because when getting more information about the item, crossref expects it without the domain. I don't know if crossref has entries with other domains, but if it does, then yes, indeed, we need that updated!

Case 2 are indeed, as you suspected, test cases. Most of those are "real life" test cases that we have come across over the years (it's end users' bibtex files) and we try to be as fault tolerant as possible with them. So it would probably be better to add more test cases rather than to "fix" existing ones. And yes, you are welcome to add those!
